-- MySQL Script generated by MySQL Workbench
-- 10/16/16 03:18:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ua_21053_fbd_s02_ex01
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ua_21053_fbd_s02_ex01` ;

-- -----------------------------------------------------
-- Schema ua_21053_fbd_s02_ex01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ua_21053_fbd_s02_ex01` DEFAULT CHARACTER SET utf8 ;
USE `ua_21053_fbd_s02_ex01` ;

-- -----------------------------------------------------
-- Table `ua_21053_fbd_s02_ex01`.`Firma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ua_21053_fbd_s02_ex01`.`Firma` ;

CREATE TABLE IF NOT EXISTS `ua_21053_fbd_s02_ex01`.`Firma` (
  `Firma_cod` INT NOT NULL,
  `Firma_nome` VARCHAR(45) NULL,
  `País` VARCHAR(45) NULL,
  PRIMARY KEY (`Firma_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ua_21053_fbd_s02_ex01`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ua_21053_fbd_s02_ex01`.`Produto` ;

CREATE TABLE IF NOT EXISTS `ua_21053_fbd_s02_ex01`.`Produto` (
  `Produto_cod` INT NOT NULL,
  `Produto_nome` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`Produto_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ua_21053_fbd_s02_ex01`.`Fornece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ua_21053_fbd_s02_ex01`.`Fornece` ;

CREATE TABLE IF NOT EXISTS `ua_21053_fbd_s02_ex01`.`Fornece` (
  `Firma_Firma_cod` INT NOT NULL,
  `Produto_Produto_cod` INT NOT NULL,
  `Preco` DOUBLE NULL,
  PRIMARY KEY (`Firma_Firma_cod`, `Produto_Produto_cod`),
  INDEX `fk_Fornece_Firma1_idx` (`Firma_Firma_cod` ASC),
  INDEX `fk_Fornece_Produto1_idx` (`Produto_Produto_cod` ASC),
  CONSTRAINT `fk_Fornece_Firma1`
    FOREIGN KEY (`Firma_Firma_cod`)
    REFERENCES `ua_21053_fbd_s02_ex01`.`Firma` (`Firma_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornece_Produto1`
    FOREIGN KEY (`Produto_Produto_cod`)
    REFERENCES `ua_21053_fbd_s02_ex01`.`Produto` (`Produto_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
