-- MySQL Script generated by MySQL Workbench
-- 10/16/16 04:22:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ua_21053_fbd_s02_ex02
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ua_21053_fbd_s02_ex02` ;

-- -----------------------------------------------------
-- Schema ua_21053_fbd_s02_ex02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ua_21053_fbd_s02_ex02` DEFAULT CHARACTER SET utf8 ;
USE `ua_21053_fbd_s02_ex02` ;

-- -----------------------------------------------------
-- Table `ua_21053_fbd_s02_ex02`.`Balcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ua_21053_fbd_s02_ex02`.`Balcao` ;

CREATE TABLE IF NOT EXISTS `ua_21053_fbd_s02_ex02`.`Balcao` (
  `n_balcao` INT NOT NULL AUTO_INCREMENT,
  `cidade_balcao` VARCHAR(45) NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`n_balcao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ua_21053_fbd_s02_ex02`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ua_21053_fbd_s02_ex02`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ua_21053_fbd_s02_ex02`.`Cliente` (
  `nome_cliente` VARCHAR(100) NOT NULL,
  `morada_cliente` VARCHAR(45) NULL,
  `cidade_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`nome_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ua_21053_fbd_s02_ex02`.`Emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ua_21053_fbd_s02_ex02`.`Emprestimo` ;

CREATE TABLE IF NOT EXISTS `ua_21053_fbd_s02_ex02`.`Emprestimo` (
  `n_emprestimo` INT NOT NULL,
  `Balcao_n_balcao` INT NOT NULL,
  `Cliente_nome_cliente` VARCHAR(100) NOT NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`n_emprestimo`, `Balcao_n_balcao`, `Cliente_nome_cliente`),
  INDEX `fk_Emprestimo_Balcao1_idx` (`Balcao_n_balcao` ASC),
  INDEX `fk_Emprestimo_Cliente1_idx` (`Cliente_nome_cliente` ASC),
  CONSTRAINT `fk_Emprestimo_Balcao1`
    FOREIGN KEY (`Balcao_n_balcao`)
    REFERENCES `ua_21053_fbd_s02_ex02`.`Balcao` (`n_balcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestimo_Cliente1`
    FOREIGN KEY (`Cliente_nome_cliente`)
    REFERENCES `ua_21053_fbd_s02_ex02`.`Cliente` (`nome_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ua_21053_fbd_s02_ex02`.`Deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ua_21053_fbd_s02_ex02`.`Deposito` ;

CREATE TABLE IF NOT EXISTS `ua_21053_fbd_s02_ex02`.`Deposito` (
  `n_conta` INT NOT NULL,
  `Balcao_n_balcao` INT NOT NULL,
  `Cliente_nome_cliente` VARCHAR(100) NOT NULL,
  `saldo` DOUBLE NULL,
  PRIMARY KEY (`n_conta`, `Balcao_n_balcao`, `Cliente_nome_cliente`),
  INDEX `fk_Deposito_Balcao_idx` (`Balcao_n_balcao` ASC),
  INDEX `fk_Deposito_Cliente1_idx` (`Cliente_nome_cliente` ASC),
  CONSTRAINT `fk_Deposito_Balcao`
    FOREIGN KEY (`Balcao_n_balcao`)
    REFERENCES `ua_21053_fbd_s02_ex02`.`Balcao` (`n_balcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deposito_Cliente1`
    FOREIGN KEY (`Cliente_nome_cliente`)
    REFERENCES `ua_21053_fbd_s02_ex02`.`Cliente` (`nome_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
